### ISSUE TITLE
Latest version (0.1.2) doesn't have latest optional parsing patch for CJS build

### ISSUE THREAD

**Issue by derekr** [kiliman/remix-params-helper#2]
Hey! The CJS build seems to be missing the patch for optional field parsing

_dist/cjs/helper.js_
<img width="736" alt="CleanShot 2022-01-07 at 11 05 25@2x" src="https://user-images.githubusercontent.com/22249/148594195-d1bc6cc8-3821-4928-a081-c2d489dce894.png">

_dist/helper.js_
<img width="875" alt="CleanShot 2022-01-07 at 11 07 19@2x" src="https://user-images.githubusercontent.com/22249/148594311-00e1616f-259f-4f38-8b61-6fd8f1267b4d.png">

Not sure why my project isn't importing the ESM build, so if there is something I may be doing wrong on my end I'd be happy to know!

**Comment by kiliman** [comment]
Pull down the latest version 0.1.3.

There was a build issue due to invalid peer dependency and 0.1.2 was published accidentally.

**Comment by derekr** [comment]
Thanks for the quick turn around 🙏🏻!
