### ISSUE TITLE
getFormData throw an error when ZodLiteral is used in schema

### ISSUE THREAD

**Issue by webflo-dev** [kiliman/remix-params-helper#20]
### Describe the bug

When a zod schema contains a field of type Literal, the method `getFormData` throw the following error:

`
Error: Unexpected type ZodLiteral for key **key_name_here**
    at processDef (/home/florent/dev/pro/scrumfit-v2/node_modules/remix-params-helper/dist/cjs/helper.js:187:15)
    at parseParams (/home/florent/dev/pro/scrumfit-v2/node_modules/remix-params-helper/dist/cjs/helper.js:31:9)
    at getParamsInternal (/home/florent/dev/pro/scrumfit-v2/node_modules/remix-params-helper/dist/cjs/helper.js:62:9)
    at getFormData (/home/florent/dev/pro/scrumfit-v2/node_modules/remix-params-helper/dist/cjs/helper.js:106:12)
`

### Your Example Website or App

https://github.com/webflo-dev/issue-zod-literal

### Steps to Reproduce the Bug or Issue

```javascript
const schema = z.object({
  someKey: z.literal('specific_value_here'),
});

try {
   const formData = await getFormData(request.clone(), schema);
   console.log(formData.success ? 'validation successful' : 'validation failed');
} catch {
   console.log('should not go here');
}

<Form method="post">
   <input type="hidden" name="someKey" value="deleteeeeee" />
   <button type="submit" name="id" value="1">delete</button>
 </Form>
```

### Expected behavior

Based on the below code, we should have log "validation failed" but we have "should not go here".

However, it works if the key is missing. But if the key is present with an unexpected value, it throw an error.

After some quick investigation, I seems that "ZodLiteral" type is not taken in account properly and the error is thrown from here: https://github.com/kiliman/remix-params-helper/blob/main/src/helper.ts#L234

### Platform

- OS: Linux
- nodeJS version 16.14.0

**Comment by kiliman** [comment]
Thanks. I'm traveling at the moment, but I will look at this over the weekend.
