### ISSUE TITLE
Support Union?

### ISSUE THREAD

**Issue by kentcdodds** [kiliman/remix-params-helper#30]
I have a base set of search params and I want to union it with another set of search params, right now that's not working for me. Here's an example:

```tsx
export const BaseSearchParamsSchema = z.object({
	query: z.string().default(''),
	exclude: z.array(z.string()).default([]),
})

const NullableNumber = z
	.string()
	.nullable()
	.optional()
	.transform(s => {
		const number = s ? Number(s) : null
		return number === null || Number.isNaN(number) ? null : number
	})

export const SearchParamsSchema = z.union([
	BaseSearchParamsSchema,
	z.object({
		lat: NullableNumber,
		long: NullableNumber,
	}),
])

export async function loader({ request }: LoaderArgs) {
	// these all show an error
	const { query, lat, long, exclude } = getSearchParamsOrFail(
		request,
		SearchParamsSchema,
	)
	// for example:
	// Property 'exclude' does not exist on type '{ exclude: string[]; query: string; } | { lat: number | null; long: number | null; }'.ts(2339)
}
```

**Comment by kiliman** [comment]
I think we discussed this on your stream. The helper will automatically coerce the *string* value into the proper type based on the schema. So if you defined a value as `z.number()`, the helper will automatically convert the string into a number. If it is not a number, the validation will fail. 

You do not need to create your own transformer for type conversions. I think you would only need that if you want to add custom logic.
