### ISSUE TITLE
Throw a json response?

### ISSUE THREAD

**Issue by binajmen** [kiliman/remix-params-helper#6]
This is not an issue, rather a discussion.

Is there a way to reduce this part (`<--`) of the code?
```ts
if (action === "save") {
  const result = getParams<SaveActionType>(formData, saveSchema);

  if (!result.success) {                            // <--
    return json(result.errors, { status: 400 });    // <--
  }                                                 // <--

  const { id, ...values } = result.data;
  await updateExam(id, values);
}
```
In fact, my real question is: does a throw in `getParams` could be captured and transformed, in some way, in the returned json via the `CatchBoundary`?

If I have several actions, it seems repetitive. Perhaps can it be improved? – I'm fully aware that at some point, things need to be written, just asking ;D

**Comment by kiliman** [comment]
I’m not sure you want to handle form validation errors in a catch boundary. The only thrown response that Remix handles directly are redirects. If you throw json (even status 200) it will go to the catch boundary and not your route component with useActionData. 

Yes it is extra code to handle the error case. Unfortunately JS doesn’t have a conditional return feature like Ruby.

**Comment by binajmen** [comment]
I wanted to challenge what I'm doing, I was pretty sure of the answer. Thanks for your feedback ;)

**Comment by kiliman** [comment]
BTW: I added helper versions that end in `OrFail()` like `getParamsOrFail`. This way if the validation fails, it will throw an Error (not a Response). This was based on a feature request.

So now you can simply do:
```ts
const { id, ...values } = await getFormDataOrFail(request, saveSchema)
```

**Comment by binajmen** [comment]
Interesting. To be used in combination with `CatchBoundary` I suppose? But it means you can't give feedbacks in a form input?

Still, handy to have this version! 👍

**Comment by kiliman** [comment]
No. This would actually go to `ErrorBoundary`. Like I've said before, I think it's better to return form validation errors, so you can display the messages.

This is if you want to fail fast... but I'm not a fan of throwing Error, since that should be reserved for ***unexpected*** errors.
